[2022-10-04 15:32:36,653] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: td-dag-test.get_data manual__2022-09-07T03:09:01.298897+00:00 [queued]>
[2022-10-04 15:32:36,979] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: td-dag-test.get_data manual__2022-09-07T03:09:01.298897+00:00 [queued]>
[2022-10-04 15:32:36,988] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-04 15:32:36,991] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2022-10-04 15:32:36,996] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-04 15:32:37,186] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): get_data> on 2022-09-07 03:09:01.298897+00:00
[2022-10-04 15:32:37,277] {standard_task_runner.py:52} INFO - Started process 5119 to run task
[2022-10-04 15:32:37,307] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'td-dag-test', 'get_data', 'manual__2022-09-07T03:09:01.298897+00:00', '--job-id', '170', '--raw', '--subdir', 'DAGS_FOLDER/td_dag_test.py', '--cfg-path', '/tmp/tmprtvuijrc', '--error-file', '/tmp/tmps6_d4oxy']
[2022-10-04 15:32:37,314] {standard_task_runner.py:80} INFO - Job 170: Subtask get_data
[2022-10-04 15:32:38,567] {task_command.py:371} INFO - Running <TaskInstance: td-dag-test.get_data manual__2022-09-07T03:09:01.298897+00:00 [running]> on host f2e7b0d61203
[2022-10-04 15:32:39,514] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=mravelo@groupon.com
AIRFLOW_CTX_DAG_OWNER=FSA
AIRFLOW_CTX_DAG_ID=td-dag-test
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-09-07T03:09:01.298897+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-07T03:09:01.298897+00:00
[2022-10-04 15:32:39,547] {logging_mixin.py:115} INFO - --- INFO: Move data process started ---
[2022-10-04 15:32:39,640] {base.py:68} INFO - Using connection ID 'teradata' for task execution.
[2022-10-04 15:34:03,510] {logging_mixin.py:115} INFO - we came back from Teradata
[2022-10-04 15:34:03,734] {logging_mixin.py:115} INFO -     environment_id  ...     last_modified_by
0           10001  ...  EMERGENOW\brobinson
1               1  ...  EMERGENOW\brobinson
2           20001  ...  EMERGENOW\brobinson

[3 rows x 17 columns]
[2022-10-04 15:34:03,740] {logging_mixin.py:115} INFO - --- INFO: Move data process complete ---
[2022-10-04 15:34:03,747] {logging_mixin.py:115} INFO - --- INFO: CSV file created ---
[2022-10-04 15:34:03,778] {python.py:173} INFO - Done. Returned value was: None
[2022-10-04 15:34:03,960] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=td-dag-test, task_id=get_data, execution_date=20220907T030901, start_date=20221004T153236, end_date=20221004T153403
[2022-10-04 15:34:04,242] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-10-04 15:34:04,255] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 5119. PIDs of all processes in the group: [5119]
[2022-10-04 15:34:04,256] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 5119
[2022-10-04 15:34:04,972] {process_utils.py:75} INFO - Process psutil.Process(pid=5119, status='terminated', exitcode=0, started='15:32:37') (5119) terminated with exit code 0
