[2023-01-26 16:06:43,704] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: jla-psp-paymentech-load.get_process_uuid manual__2023-01-26T16:06:19.954611+00:00 [queued]>
[2023-01-26 16:06:43,744] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: jla-psp-paymentech-load.get_process_uuid manual__2023-01-26T16:06:19.954611+00:00 [queued]>
[2023-01-26 16:06:43,746] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-01-26 16:06:43,748] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-01-26 16:06:43,749] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-01-26 16:06:43,819] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): get_process_uuid> on 2023-01-26 16:06:19.954611+00:00
[2023-01-26 16:06:43,831] {standard_task_runner.py:52} INFO - Started process 22020 to run task
[2023-01-26 16:06:43,842] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'jla-psp-paymentech-load', 'get_process_uuid', 'manual__2023-01-26T16:06:19.954611+00:00', '--job-id', '210', '--raw', '--subdir', 'DAGS_FOLDER/jla-psp-paymentech-load.py', '--cfg-path', '/tmp/tmpjgkkad8f', '--error-file', '/tmp/tmpr_c6m76f']
[2023-01-26 16:06:43,845] {standard_task_runner.py:80} INFO - Job 210: Subtask get_process_uuid
[2023-01-26 16:06:44,181] {task_command.py:371} INFO - Running <TaskInstance: jla-psp-paymentech-load.get_process_uuid manual__2023-01-26T16:06:19.954611+00:00 [running]> on host 3d21fd43a943
[2023-01-26 16:06:44,802] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=barobinson@groupon.com
AIRFLOW_CTX_DAG_OWNER=FSA
AIRFLOW_CTX_DAG_ID=jla-psp-paymentech-load
AIRFLOW_CTX_TASK_ID=get_process_uuid
AIRFLOW_CTX_EXECUTION_DATE=2023-01-26T16:06:19.954611+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-26T16:06:19.954611+00:00
[2023-01-26 16:06:45,095] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/jla-psp-paymentech-load.py", line 147, in get_process_uuid__func
    kwargs['ti'].xcom_push(key="slack_webhook_token", value=BaseHook.get_connection(DEFAULT_ARGS['slack_conn_id']).password)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `slack_connection` isn't defined
[2023-01-26 16:06:45,132] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=jla-psp-paymentech-load, task_id=get_process_uuid, execution_date=20230126T160619, start_date=20230126T160643, end_date=20230126T160645
[2023-01-26 16:06:45,191] {standard_task_runner.py:97} ERROR - Failed to execute job 210 for task get_process_uuid (The conn_id `slack_connection` isn't defined; 22020)
[2023-01-26 16:06:45,230] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-01-26 16:06:45,563] {xcom.py:586} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2023-01-26 16:06:45,590] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-01-26 16:06:45,593] {logging_mixin.py:115} INFO - :ampelred: AIRFLOW TASK FAILURE :ampelred:

DAG:                             jla-psp-paymentech-load
TASKS:                          get_process_uuid
EXECUTION TIME:      2023-01-26T16:06:19.954611+00:00
REASON:                       The conn_id `slack_connection` isn't defined
LOG:                              http://localhost:8080/log?execution_date=2023-01-26T16%3A06%3A19.954611%2B00%3A00&task_id=get_process_uuid&dag_id=jla-psp-paymentech-load&map_index=-1
[2023-01-26 16:06:45,654] {logging_mixin.py:115} INFO - slack_connection
[2023-01-26 16:06:45,655] {logging_mixin.py:115} INFO - None
[2023-01-26 16:06:45,656] {logging_mixin.py:115} INFO - None
[2023-01-26 16:06:45,669] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/http/operators/http.py:83: DeprecationWarning: none_failed_or_skipped Trigger Rule is deprecated. Please use `none_failed_min_one_success`.
  super().__init__(**kwargs)

[2023-01-26 16:06:45,702] {taskinstance.py:1752} ERROR - Error when executing on_failure_callback
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1750, in _run_finished_callback
    task.on_failure_callback(context)
  File "/opt/airflow/dags/utils/Error.py", line 137, in failure_callback
    failed_alert.execute(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/slack/operators/slack_webhook.py", line 107, in execute
    self.proxy,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/slack/hooks/slack_webhook.py", line 75, in __init__
    self.webhook_token = self._get_token(webhook_token, http_conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/slack/hooks/slack_webhook.py", line 98, in _get_token
    conn = self.get_connection(http_conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `slack_connection` isn't defined
[2023-01-26 16:06:45,924] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
